### ISSUE TITLE
what is library todomvc

### ISSUE THREAD

**Issue by dsourav** [flutter-institute/todomvc#2]
what is the use of library todomvc and part of todomvc.where is the material dart package in some of the dart file.

**Comment by killermonk** [comment]
@dsourav 

I created this app as a Library Package
https://www.dartlang.org/guides/libraries/create-library-packages
https://www.dartlang.org/tools/pub/glossary#library-package

I did this, partially, so that I didn't have to duplicate all the imports in the files that use `part of`.

The material dart package is imported into the library here: https://github.com/flutter-institute/todomvc/blob/master/lib/src/todo_app.dart#L10
All of the other files that are `part` of the library inherit those imports. The end of the parts list is here: https://github.com/flutter-institute/todomvc/blob/master/lib/src/todo_app.dart#L21

Each of those files that I specify as a `part` in todo_app.dart then must also specify themselves as `part of` the library. You'll notice that none of the files that are `part of` the library actually have any imports. All of those imports are handled in `todo_app.dart` when the library is created.

Does that make sense?
